# Generated by Django 4.1 on 2025-02-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamento",
            name="sigla",
            field=models.CharField(max_length=10),
        ),
    ]
